apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: finance-db-statefulset
spec:
  selector:
    matchLabels:
      app: finance-db
  serviceName: finance-api-db
  replicas: 1
  template:
    metadata:
      labels:
        app: finance-db
    spec:
      containers:
        - name: postgresql
          image: postgres:latest
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: db-finance-configmap
          readinessProbe:
            exec:
              command:
                - "pg_isready"
                - "-U"
                - "postgres"
                - "-d"
                - "finance-db"
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 3
          resources:
            limits:
              cpu: "2"
              memory: "2Gi"
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: db-data
      volumes:
        - name: db-data
          persistentVolumeClaim:
            claimName: local-storage
