apiVersion: v1
kind: Service
metadata:
  name: finance-api-db
spec:
  type: ClusterIP
  selector:
    app: finance-db
  ports:
  - port: 5432
    targetPort: 5432

---

apiVersion: v1
kind: Service
metadata:
  name: svc-finance-external
spec:
  type: NodePort
  selector:
    app: finance-api
  ports:
  - port: 8085
    nodePort: 30000