apiVersion: v1
kind: ConfigMap
metadata:
  name: db-finance-configmap
data:
  POSTGRES_DB: finance-db
  PGUSER: postgres
  POSTGRES_PASSWORD: rootDB1234!
  LANG: en_US.utf8

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: app-finance-configmap
data:
  DATABASE_URL: postgresql://postgres:rootDB1234!@finance-api-db:5432/finance-db